In [11]:
# Task 1: Write a program that allows you to enter 4 numbers and stores them in a file called “Numbers”.

numbers = open("numbers.txt","w")
numbers.write(str("8,19,32,57"))


numbers.close()

In [60]:
# Task 2: Write a program to ask a student for their percentage mark and convert this to a grade.
# The conversion will be done in a function called mark_grade

def function1():

    student_mark = int(input("Please enter your percentage mark to receive your grade"))

    if student_mark <= 100 and student_mark >= 80:
        print("A")
    elif student_mark >= 70 and student_mark < 80:
        print("B")
    elif student_mark >= 60 and student_mark < 70:
        print("C")
    elif student_mark >= 40 and student_mark < 60:
        print("D")
    elif student_mark < 40:
        print("F")
    else:
        print("Please try again.")

function1()

C


In [3]:
# Extension of task 2

def function2():

    target_mark = str(input("What is your target grade?"))
    student_mark = int(input("Please enter your percentage mark to receive your grade"))
    

    if (target_mark == "A") and (student_mark <= 100 and student_mark >= 80):
        print("Congratulations, you achieved your target mark of A")
    elif (target_mark == "B" or "C" or "D") and (student_mark <= 100 and student_mark >= 80):
        print("Amazing work, you've excelled and achieved an A")
    elif (target_mark == "B") and (student_mark >= 70 and student_mark < 80):
        print("Congratulations, you achieved your target mark of B")
    elif (target_mark == "A") and (student_mark >= 70 and student_mark < 80):
        print("Unfortunately you underachieved with a B")
    elif (target_mark == "C" or "D" or "E") and (student_mark >= 70 and student_mark < 80):
        Print("Amazing work, you've excelled and achieved a B")
    elif (target_mark =="C") and (student_mark >= 60 and student_mark < 70):
        print("Congratulations, you achieved your target mark of C")
    elif (target_mark =="D" or "E") and (student_mark >= 60 and student_mark < 70):
        print("Amazing work, you've excelled and achieved a C")
    elif (target_mark =="A" or "B") and (student_mark >= 60 and student_mark < 70):
        print("Unfortunately you underachieved with a C")
    elif (target_mark =="D") and (student_mark >= 40 and student_mark < 60):
        print("Congratulations, you achieved your target mark of D")
    elif (target_mark =="E") and (student_mark >= 40 and student_mark < 60):
        print("Amazing work, you've excelled and achieved a D")
    elif (target_mark =="A" or "B" or "C") and (student_mark >= 40 and student_mark < 60):
        print("Unfortunately you underachieved with a D")
    elif (student_mark < 40):
        print("Unfortunately you failed")
    else:
        print("Please try again.")

function2()

Unfortunately you underachieved with a B


In [10]:
import numpy as np

# Task 1: Create a 1D array of numbers from 0 to 9

array = np.array([1,2,3,4,5,6,7,8,9])

print(array)

[1 2 3 4 5 6 7 8 9]


In [14]:
# Task 2: Create a 3×3 NumPy array of all Boolean value Trues

bool_array = np.ones(9, dtype=bool)

new_bool_array = bool_array.reshape(3,3)

print(new_bool_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [39]:
# Task 3: Extract all odd numbers from array of 1-10


extract_array = np.arange(1,11,2)

print(extract_array)

[1 3 5 7 9]


In [37]:
# Task 4: Replace all odd numbers in an array of 1-10 with the value -1

array[array%2 ==1] = -1

print(array)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [51]:
# Task 5: Convert a 1D array to a 2D array with 2 rows.

task5array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

reshaped_array = task5array.reshape(2,10)

print(reshaped_array)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [77]:
# Task 6: Create two arrays a and b, stack these two arrays vertically use the  np.dot and np.sum to calculate totals.

task6array1 = np.arange(0,16).reshape(4,4)
task6array2 = np.arange(17,33).reshape(4,4)
stack = np.dot(task6array1, task6array2)
sum = np.sum(stack)

print(sum)

12080


In [78]:
# Extension 1: Create the following pattern without hardcoding. Use only NumPy functions.

a = np.array([1, 2, 3])

np.append(np.repeat(a,3), np.tile(a,3))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [81]:
# Extension 2: In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) –remove all repeating  items present in array b.

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])

# Sorry, I'm lost with this one!

[1 2 3 4 5]


In [ ]:
# Extension 3: Get all items between 3 and 7 from a and b and sum them together.

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])

# Unsure on the question? Is it asking to sum the numbers between the 3rd and 7th positions or is it asking to sum the numbers between 3 and 7?